In [1]:
import os
import sys

## Add convida lib and convida server lib to path
convida_lib_path = os.path.dirname(os.getcwd())
lib = os.path.join(convida_lib_path,'lib')
sys.path.append(lib)

#for path in sys.path:
#    print(path)

In [2]:
from convida_server import convida_server
from convida import COnVIDa
from regions import Regions
from datatype import DataType
import pandas as pd

## Testing

In [3]:
convida_server.init_log()
convida_server.load_data()
print(convida_server.get_min_date())
print(convida_server.get_max_date())

2020-11-01
2020-12-30

### Temporal requests

In [4]:
print('Testing temporal requests...')

all_regions = Regions.get_regions('ES')
print(all_regions)
datasources = COnVIDa.get_data_items_names(DataType.TEMPORAL, language='EN')
all_data_items = []
for data_items in datasources.values():
    all_data_items += data_items
    
start_date = pd.to_datetime('2020-11-01', format='%Y-%m-%d')
print('START DATE: ', start_date)
end_date = pd.to_datetime('2020-12-30', format='%Y-%m-%d')
print('END DATE: ', end_date)

Testing temporal requests...
['España', 'CA Andalucía', 'CA Aragón', 'CA Principado de Asturias', 'CA Islas Baleares', 'CA Canarias', 'CA Cantabria', 'CA Castilla-La Mancha', 'CA Castilla y León', 'CA Cataluña', 'CA Ceuta', 'CA Comunidad Valenciana', 'CA Extremadura', 'CA Galicia', 'CA Comunidad de Madrid', 'CA Melilla', 'CA Región de Murcia', 'CA Comunidad Foral de Navarra', 'CA País Vasco', 'CA La Rioja', 'Albacete', 'Alicante', 'Almería', 'Álava', 'Asturias', 'Ávila', 'Badajoz', 'Baleares', 'Barcelona', 'Bizkaia', 'Burgos', 'Cáceres', 'Cádiz', 'Cantabria', 'Castellón', 'Ciudad Real', 'Córdoba', 'A Coruña', 'Cuenca', 'Gipuzkoa', 'Girona', 'Granada', 'Guadalajara', 'Huelva', 'Huesca', 'Jaén', 'León', 'Lleida', 'Lugo', 'Madrid', 'Málaga', 'Murcia', 'Navarra', 'Ourense', 'Palencia', 'Las Palmas', 'Pontevedra', 'La Rioja', 'Salamanca', 'Santa Cruz de Tenerife', 'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia', 'Valladolid', 'Zamora', 'Zaragoza', 'Ceuta', 'Melilla']
START DATE:  2020-11-01 00:00:00
END DATE:  2020-12-30 00:00:00

In [5]:
data = convida_server.get_data_items(data_items=[all_data_items[0]],
                              regions=all_regions,
                              start_date=start_date,
                              end_date=end_date,
                              language='EN')
display(data.head(2))
display(data.tail(10))

Region,CA Andalucía,CA Aragón,CA Canarias,CA Cantabria,CA Castilla y León,CA Castilla-La Mancha,CA Cataluña,CA Ceuta,CA Comunidad Foral de Navarra,CA Comunidad Valenciana,CA Comunidad de Madrid,CA Extremadura,CA Galicia,CA Islas Baleares,CA La Rioja,CA Melilla,CA País Vasco,CA Principado de Asturias,CA Región de Murcia
Item,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall
2020-11-01,0.000000,0.000000,0.000000,0.000000,0.018182,0.0,0.020000,0.0,0.0,0.014286,0.000000,0.018182,5.853333,0.02,NaN,0.0,0.000000,0.009091,0.010000
2020-11-02,0.013889,0.692308,0.005882,7.971429,2.340909,0.0,0.007143,0.0,0.9,0.000000,0.369231,0.060000,4.753333,0.01,0.8,0.0,8.354545,7.900000,0.011111

Region,CA Andalucía,CA Aragón,CA Canarias,CA Cantabria,CA Castilla y León,CA Castilla-La Mancha,CA Cataluña,CA Ceuta,CA Comunidad Foral de Navarra,CA Comunidad Valenciana,CA Comunidad de Madrid,CA Extremadura,CA Galicia,CA Islas Baleares,CA La Rioja,CA Melilla,CA País Vasco,CA Principado de Asturias,CA Región de Murcia
Item,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall,Rainfall
2020-12-21,0.025714,0.009091,0.075000,0.100000,0.154167,0.110526,0.166667,0.0,1.040,0.000000,0.633333,0.100000,4.053846,0.000000,1.1,0.0,0.316667,0.000000,0.000000
2020-12-22,0.005714,0.000000,0.000000,0.014286,0.095652,0.080000,0.026667,0.0,0.040,0.000000,0.053846,0.045455,10.986667,0.022222,0.1,0.0,0.009091,0.166667,0.000000
2020-12-23,0.000000,0.046154,0.000000,3.028571,1.030435,0.063158,0.014286,0.0,0.760,0.000000,1.046154,0.336364,1.813333,0.000000,0.6,0.0,5.425000,2.672727,0.000000
2020-12-24,0.017143,0.261538,0.000000,9.257143,0.213043,0.595000,0.053846,0.0,6.475,0.176923,0.376923,0.140000,1.513333,0.371429,0.1,0.0,16.133333,14.054545,0.000000
2020-12-25,0.008571,0.015385,1.141176,2.400000,0.254167,0.085000,0.500000,0.0,2.260,0.007692,0.000000,0.000000,0.028571,4.066667,0.0,1.2,4.600000,1.681818,0.000000
2020-12-26,0.000000,0.000000,1.964706,1.000000,0.008333,0.010000,0.026667,0.0,0.000,0.000000,0.000000,0.000000,0.013333,0.066667,0.1,0.0,0.830000,0.054545,0.000000
2020-12-27,0.159459,5.907692,0.100000,22.885714,4.452000,2.431579,0.780000,0.0,8.660,0.550000,2.625000,1.163636,11.060000,0.075000,4.1,0.0,26.775000,21.188889,0.000000
2020-12-28,2.642857,5.076923,0.005882,16.500000,0.933333,1.160000,0.340000,10.4,3.100,0.284615,0.009091,0.440000,9.353333,0.312500,0.0,3.0,16.700000,22.600000,0.212500
2020-12-29,0.431429,2.961538,0.043750,28.928571,0.686957,0.522222,0.366667,2.6,10.400,0.000000,0.625000,0.118182,3.393333,1.588889,NaN,1.6,31.258333,19.544444,0.311111
2020-12-30,0.011111,2.633333,0.973333,3.685714,0.212000,0.180000,0.353333,0.0,2.960,0.000000,0.750000,0.018182,8.773333,0.000000,0.0,0.0,8.775000,1.155556,0.000000

In [6]:
print('Testing temporal requests...')

all_regions = Regions.get_regions('ES')

datasources = COnVIDa.get_data_items_names(DataType.TEMPORAL, language='ES')
all_data_items = []
for data_items in datasources.values():
    all_data_items += data_items

Testing temporal requests...

### Testing geographical requests

In [7]:
print('Testing geographical requests...')

all_regions = Regions.get_regions('ES')

datasources = COnVIDa.get_data_items_names(DataType.GEOGRAPHICAL)
all_data_items = []
for data_items in datasources.values():
    all_data_items += data_items
print(all_data_items)

Testing geographical requests...
['Actividad física', 'Índice de masa corporal (IMC)', 'Tabaquismo', 'Hogares por tipo de familia', 'Hogares por densidad de ocupación', 'Mayores de 65 años solos']

In [8]:
data = convida_server.get_data_items(data_items=[all_data_items[0]],
                              regions=all_regions)
display(data.head(2))
display(data.tail(2))

Item,Actividad física (Nivel alto),Actividad física (Nivel bajo),Actividad física (Nivel moderado),Actividad física (No consta)
Region,,,,
CA Andalucía,1207.9,2558.3,2206.7,0.0
CA Aragón,98.7,400.2,403.2,1.1

Item,Actividad física (Nivel alto),Actividad física (Nivel bajo),Actividad física (Nivel moderado),Actividad física (No consta)
Region,,,,
Ceuta,8.3,44.5,7.4,0.0
Melilla,33.9,6.1,17.9,0.0

In [9]:
data = convida_server.get_data_items(data_items=all_data_items,
                              regions=all_regions)
display(data.head(2))
display(data.tail(2))

Item,Actividad física (Nivel alto),Actividad física (Nivel bajo),Actividad física (Nivel moderado),Actividad física (No consta),Hogares por densidad de ocupación (60 m2 o más por ocupante),Hogares por densidad de ocupación (Entre 10 y menos de 20 m2 por ocupante),Hogares por densidad de ocupación (Entre 20 y menos de 30 m2 por ocupante),Hogares por densidad de ocupación (Entre 30 y menos de 60 m2 por ocupante),Hogares por densidad de ocupación (Menos de 10 m2 por ocupante),Hogares por tipo de familia (1 persona),...,"Mayores de 65 años solos (65 años o más, Viudo/a)","Mayores de 65 años solos (Menos de 65 años, Casado/a)","Mayores de 65 años solos (Menos de 65 años, Divorciado/a)","Mayores de 65 años solos (Menos de 65 años, Separado/a)","Mayores de 65 años solos (Menos de 65 años, Soltero/a)","Mayores de 65 años solos (Menos de 65 años, Viudo/a)",Tabaquismo (Exfumador),Tabaquismo (Fumador diario),Tabaquismo (Fumador ocasional),Tabaquismo (Nunca ha fumado)
Region,,,,,,,,,,,,,,,,,,,,,
CA Andalucía,1207.9,2558.3,2206.7,0.0,1309.500000,1259.20,2471.483333,3266.900000,39.833333,731.866667,...,210.550000,33.566667,63.100000,23.233333,282.416667,25.483333,18.55,27.09,3.11,51.25
CA Aragón,98.7,400.2,403.2,1.1,233.833333,192.25,369.700000,497.283333,3.766667,145.833333,...,45.133333,7.516667,10.166667,4.500000,54.616667,4.366667,26.54,25.87,1.44,46.15

Item,Actividad física (Nivel alto),Actividad física (Nivel bajo),Actividad física (Nivel moderado),Actividad física (No consta),Hogares por densidad de ocupación (60 m2 o más por ocupante),Hogares por densidad de ocupación (Entre 10 y menos de 20 m2 por ocupante),Hogares por densidad de ocupación (Entre 20 y menos de 30 m2 por ocupante),Hogares por densidad de ocupación (Entre 30 y menos de 60 m2 por ocupante),Hogares por densidad de ocupación (Menos de 10 m2 por ocupante),Hogares por tipo de familia (1 persona),...,"Mayores de 65 años solos (65 años o más, Viudo/a)","Mayores de 65 años solos (Menos de 65 años, Casado/a)","Mayores de 65 años solos (Menos de 65 años, Divorciado/a)","Mayores de 65 años solos (Menos de 65 años, Separado/a)","Mayores de 65 años solos (Menos de 65 años, Soltero/a)","Mayores de 65 años solos (Menos de 65 años, Viudo/a)",Tabaquismo (Exfumador),Tabaquismo (Fumador diario),Tabaquismo (Fumador ocasional),Tabaquismo (Nunca ha fumado)
Region,,,,,,,,,,,,,,,,,,,,,
Ceuta,8.3,44.5,7.4,0.0,4.383333,30.500000,24.016667,18.800000,6.383333,4.633333,...,1.350000,0.333333,0.533333,0.150000,1.683333,0.083333,18.62,18.66,2.13,60.59
Melilla,33.9,6.1,17.9,0.0,6.283333,27.166667,23.850000,20.433333,5.750000,4.550000,...,1.283333,0.300000,0.416667,0.133333,1.683333,0.166667,2.55,18.99,1.66,76.80

In [10]:
data = convida_server.get_data_items(data_items=all_data_items,
                              regions=all_regions)
display(data.head(2))
display(data.tail(2))

Item,Actividad física (Nivel alto),Actividad física (Nivel bajo),Actividad física (Nivel moderado),Actividad física (No consta),Hogares por densidad de ocupación (60 m2 o más por ocupante),Hogares por densidad de ocupación (Entre 10 y menos de 20 m2 por ocupante),Hogares por densidad de ocupación (Entre 20 y menos de 30 m2 por ocupante),Hogares por densidad de ocupación (Entre 30 y menos de 60 m2 por ocupante),Hogares por densidad de ocupación (Menos de 10 m2 por ocupante),Hogares por tipo de familia (1 persona),...,"Mayores de 65 años solos (65 años o más, Viudo/a)","Mayores de 65 años solos (Menos de 65 años, Casado/a)","Mayores de 65 años solos (Menos de 65 años, Divorciado/a)","Mayores de 65 años solos (Menos de 65 años, Separado/a)","Mayores de 65 años solos (Menos de 65 años, Soltero/a)","Mayores de 65 años solos (Menos de 65 años, Viudo/a)",Tabaquismo (Exfumador),Tabaquismo (Fumador diario),Tabaquismo (Fumador ocasional),Tabaquismo (Nunca ha fumado)
Region,,,,,,,,,,,,,,,,,,,,,
CA Andalucía,1207.9,2558.3,2206.7,0.0,1309.500000,1259.20,2471.483333,3266.900000,39.833333,731.866667,...,210.550000,33.566667,63.100000,23.233333,282.416667,25.483333,18.55,27.09,3.11,51.25
CA Aragón,98.7,400.2,403.2,1.1,233.833333,192.25,369.700000,497.283333,3.766667,145.833333,...,45.133333,7.516667,10.166667,4.500000,54.616667,4.366667,26.54,25.87,1.44,46.15

Item,Actividad física (Nivel alto),Actividad física (Nivel bajo),Actividad física (Nivel moderado),Actividad física (No consta),Hogares por densidad de ocupación (60 m2 o más por ocupante),Hogares por densidad de ocupación (Entre 10 y menos de 20 m2 por ocupante),Hogares por densidad de ocupación (Entre 20 y menos de 30 m2 por ocupante),Hogares por densidad de ocupación (Entre 30 y menos de 60 m2 por ocupante),Hogares por densidad de ocupación (Menos de 10 m2 por ocupante),Hogares por tipo de familia (1 persona),...,"Mayores de 65 años solos (65 años o más, Viudo/a)","Mayores de 65 años solos (Menos de 65 años, Casado/a)","Mayores de 65 años solos (Menos de 65 años, Divorciado/a)","Mayores de 65 años solos (Menos de 65 años, Separado/a)","Mayores de 65 años solos (Menos de 65 años, Soltero/a)","Mayores de 65 años solos (Menos de 65 años, Viudo/a)",Tabaquismo (Exfumador),Tabaquismo (Fumador diario),Tabaquismo (Fumador ocasional),Tabaquismo (Nunca ha fumado)
Region,,,,,,,,,,,,,,,,,,,,,
Ceuta,8.3,44.5,7.4,0.0,4.383333,30.500000,24.016667,18.800000,6.383333,4.633333,...,1.350000,0.333333,0.533333,0.150000,1.683333,0.083333,18.62,18.66,2.13,60.59
Melilla,33.9,6.1,17.9,0.0,6.283333,27.166667,23.850000,20.433333,5.750000,4.550000,...,1.283333,0.300000,0.416667,0.133333,1.683333,0.166667,2.55,18.99,1.66,76.80

## TESTING UPDATE

In [11]:
convida_server.init_log()
convida_server.load_data()

In [12]:
print(convida_server.get_min_date())
print(convida_server.get_max_date())
display(convida_server.get_last_update_dates())

2020-11-01
2020-12-30

                   last_update
AEMETDataSource           None
COVID19DataSource         None
INEDataSource             None
MobilityDataSource        None
MoMoDataSource            None

In [13]:
%%time
convida_server.daily_update()
convida_server.init_log()
convida_server.load_data()
display(convida_server.get_last_update_dates())

Assumed a GEOGRAPHICAL data retrieval...
Assumed a TEMPORAL data retrieval...

C:\Users\Javier\OneDrive\Documentos\Proyectos\COnVIDa-lib\lib\datasources\COVID19DataSource.py:284: RuntimeWarning: divide by zero encountered in double_scalars
  percent = (df.loc[idx, ('España', param)] * 100) / valor
C:\Users\Javier\OneDrive\Documentos\Proyectos\COnVIDa-lib\lib\datasources\COVID19DataSource.py:284: RuntimeWarning: invalid value encountered in double_scalars
  percent = (df.loc[idx, ('España', param)] * 100) / valor
C:\Users\Javier\anaconda3\envs\COVID19\lib\site-packages\pandas\core\generic.py:2505: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->datetime,key->block0_values] [items->Index(['last_update'], dtype='object')]

  encoding=encoding,

                   last_update
AEMETDataSource     2021-01-17
COVID19DataSource   2021-01-17
INEDataSource       2021-01-17
MobilityDataSource  2021-01-17
MoMoDataSource      2021-01-17

Wall time: 2min 43s

### AFTER UPDATE: Testing temporal requests

In [14]:
print('Testing temporal requests...')

all_regions = Regions.get_regions('ES')

datasources = COnVIDa.get_data_items_names(DataType.TEMPORAL)
all_data_items = []
for data_items in datasources.values():
    all_data_items += data_items
    
start_date = pd.to_datetime('2020-11-01', format='%Y-%m-%d')
print('START DATE: ', start_date)
end_date = pd.to_datetime(pd.to_datetime('2021-01-16').strftime(format='%Y-%m-%d'))

print('END DATE: ', end_date)

Testing temporal requests...
START DATE:  2020-11-01 00:00:00
END DATE:  2021-01-16 00:00:00

In [15]:
data = convida_server.get_data_items(data_items=[all_data_items[0:5]],
                              regions=all_regions[0:5],
                              start_date=start_date,
                              end_date=end_date)
display(data.head(2))
display(data.tail(2))

WARNING. Item ['Precipitación', 'Presión máxima', 'Presión mínima', 'Racha máxima', 'Insolación'] is not TEMPORAL data

Region              CA Andalucía                                             \
Item       accumulated_lethality     altitud cases_14days cases_accumulated
2020-11-01               0.01733  288.526316      49576.0          148376.0
2020-11-02               0.01705  288.526316      52293.0          152801.0

Region                                                               \
Item       cases_accumulated_PCR cases_per_cienmil daily_cases_avg7
2020-11-01                   NaN           1763.39           4129.3
2020-11-02                   NaN           1815.98           4379.3

Region                                                       ...  \
Item       daily_deaths daily_deaths_avg3 daily_deaths_avg7  ...
2020-11-01         12.0              35.0              33.7  ...
2020-11-02         34.0              33.3              36.7  ...

Region                           España                         \
Item       num_casos_prueba_desconocida num_casos_prueba_elisa
2020-11-01                       1642.0                    6.0
2020-11-02                       1890.0                   14.0

Region                                                     \
Item       num_casos_prueba_pcr num_casos_prueba_pcr_avg7
2020-11-01              12705.0              16480.714286
2020-11-02              15638.0              16160.000000

Region                                                                  \
Item       num_casos_prueba_test_ac pob_vaccine_supplied_inc recovered
2020-11-01                      0.0                      NaN  109181.0
2020-11-02                      1.0                      NaN  187069.0

Region
Item       vaccine_provided vaccine_supplied vaccine_supplied_inc
2020-11-01              NaN              NaN                  NaN
2020-11-02              NaN              NaN                  NaN

[2 rows x 209 columns]

Region              CA Andalucía                                         \
Item       accumulated_lethality altitud cases_14days cases_accumulated
2021-01-15               0.01775     NaN      41668.0          310705.0
2021-01-16                   NaN     NaN          NaN               NaN

Region                                                               \
Item       cases_accumulated_PCR cases_per_cienmil daily_cases_avg7
2021-01-15                   NaN           3692.61           4268.7
2021-01-16                   NaN               NaN              NaN

Region                                                       ...  \
Item       daily_deaths daily_deaths_avg3 daily_deaths_avg7  ...
2021-01-15         43.0              35.7              31.9  ...
2021-01-16          NaN               NaN               NaN  ...

Region                           España                         \
Item       num_casos_prueba_desconocida num_casos_prueba_elisa
2021-01-15                          0.0                    0.0
2021-01-16                          NaN                    NaN

Region                                                     \
Item       num_casos_prueba_pcr num_casos_prueba_pcr_avg7
2021-01-15                  0.0               6335.714286
2021-01-16                  NaN                       NaN

Region                                                                  \
Item       num_casos_prueba_test_ac pob_vaccine_supplied_inc recovered
2021-01-15                      0.0                     1.64  427838.0
2021-01-16                      NaN                      NaN       NaN

Region
Item       vaccine_provided vaccine_supplied vaccine_supplied_inc
2021-01-15        1139400.0         768950.0            67.487274
2021-01-16              NaN              NaN                  NaN

[2 rows x 209 columns]

In [16]:
data = convida_server.get_data_items(data_items=all_data_items,
                              regions=[all_regions[0]],
                              start_date=start_date,
                              end_date=end_date)
display(data.head(2))
display(data.tail(8))

Region                  España                                          \
Item       Letalidad acumulada Casos detectados en los últimos 14 días
2020-11-01                0.03                                251770.0
2020-11-02                0.03                                266700.0

Region                                            \
Item       Casos acumulados Casos acumulados PCR
2020-11-01        1320103.0             898933.0
2020-11-02        1337586.0             908986.0

Region                                              \
Item       Casos acumulados por 100.000 habitantes
2020-11-01                                 2823.46
2020-11-02                                 2860.85

Region                                                             \
Item       Media de casos detectados en 7 días Fallecidos diarios
2020-11-01                        20084.000000              214.0
2020-11-02                        19637.714286              299.0

Region                                                \
Item       Media de fallecidos en los últimos 3 días
2020-11-01                                244.666667
2020-11-02                                255.333333

Region                                                \
Item       Media de fallecidos en los últimos 7 días
2020-11-01                                241.571429
2020-11-02                                250.000000

Region                                                               ...  \
Item       Porcentaje de nuevos fallecidos respecto de día anterior  ...
2020-11-01                                              84.58        ...
2020-11-02                                             139.72        ...

Region                                                                       \
Item       Casos diarios de pruebas desconocidas Casos diarios prueba Elisa
2020-11-01                                1642.0                        6.0
2020-11-02                                1890.0                       14.0

Region                        \
Item       Casos diarios PCR
2020-11-01           12705.0
2020-11-02           15638.0

Region                                                           \
Item       Media de casos PCR confirmados en los últimos 7 días
2020-11-01                                       16480.714286
2020-11-02                                       16160.000000

Region                                                                 \
Item       Casos diarios anticuerpos Porcentaje de población vacunada
2020-11-01                       0.0                              NaN
2020-11-02                       1.0                              NaN

Region                                                                \
Item       Casos acumulados recuperados Vacunas entregadas acumulado
2020-11-01                     109181.0                          NaN
2020-11-02                     187069.0                          NaN

Region
Item       Vacunas suministradas acumulado Porcentaje de vacunas suministradas
2020-11-01                             NaN                                 NaN
2020-11-02                             NaN                                 NaN

[2 rows x 29 columns]

Region                  España                                          \
Item       Letalidad acumulada Casos detectados en los últimos 14 días
2021-01-09                0.03                                200787.0
2021-01-10                0.03                                206395.0
2021-01-11                0.03                                235607.0
2021-01-12                0.03                                244276.0
2021-01-13                0.03                                255362.0
2021-01-14                0.03                                254595.0
2021-01-15                0.02                                113196.0
2021-01-16                 NaN                                     NaN

Region                                            \
Item       Casos acumulados Casos acumulados PCR
2021-01-09        2024867.0            1280379.0
2021-01-10        2015917.0            1284947.0
2021-01-11        2176561.0            1302283.0
2021-01-12        2203366.0            1316565.0
2021-01-13        2234263.0            1331861.0
2021-01-14        2264502.0            1345649.0
2021-01-15         830545.0             303830.0
2021-01-16              NaN                  NaN

Region                                              \
Item       Casos acumulados por 100.000 habitantes
2021-01-09                                 4330.82
2021-01-10                                 4311.68
2021-01-11                                 4655.27
2021-01-12                                 4712.60
2021-01-13                                 4778.68
2021-01-14                                 4843.36
2021-01-15                                 1776.39
2021-01-16                                     NaN

Region                                                             \
Item       Media de casos detectados en 7 días Fallecidos diarios
2021-01-09                        18993.285714              207.0
2021-01-10                        19097.000000              152.0
2021-01-11                        18747.000000              257.0
2021-01-12                        17639.714286              296.0
2021-01-13                        16949.571429              210.0
2021-01-14                        14047.857143              176.0
2021-01-15                        10494.428571               98.0
2021-01-16                                 NaN                NaN

Region                                                \
Item       Media de fallecidos en los últimos 3 días
2021-01-09                                236.000000
2021-01-10                                213.333333
2021-01-11                                205.333333
2021-01-12                                235.000000
2021-01-13                                254.333333
2021-01-14                                227.333333
2021-01-15                                161.333333
2021-01-16                                       NaN

Region                                                \
Item       Media de fallecidos en los últimos 7 días
2021-01-09                                216.428571
2021-01-10                                225.857143
2021-01-11                                227.142857
2021-01-12                                228.714286
2021-01-13                                231.857143
2021-01-14                                225.571429
2021-01-15                                199.428571
2021-01-16                                       NaN

Region                                                               ...  \
Item       Porcentaje de nuevos fallecidos respecto de día anterior  ...
2021-01-09                                              73.67        ...
2021-01-10                                              73.43        ...
2021-01-11                                             169.08        ...
2021-01-12                                             115.18        ...
2021-01-13                                              70.95        ...
2021-01-14                                              83.81        ...
2021-01-15                                              55.68        ...
2021-01-16                                                NaN        ...

Region                                                                       \
Item       Casos diarios de pruebas desconocidas Casos diarios prueba Elisa
2021-01-09                                3596.0                        2.0
2021-01-10                                3548.0                        1.0
2021-01-11                                5193.0                        6.0
2021-01-12                                4711.0                        6.0
2021-01-13                                4703.0                        2.0
2021-01-14                                   4.0                        0.0
2021-01-15                                   0.0                        0.0
2021-01-16                                   NaN                        NaN

Region                        \
Item       Casos diarios PCR
2021-01-09           11279.0
2021-01-10            8409.0
2021-01-11           10234.0
2021-01-12           10106.0
2021-01-13            4312.0
2021-01-14              10.0
2021-01-15               0.0
2021-01-16               NaN

Region                                                           \
Item       Media de casos PCR confirmados en los últimos 7 días
2021-01-09                                       12229.000000
2021-01-10                                       12270.285714
2021-01-11                                       11941.142857
2021-01-12                                       11098.428571
2021-01-13                                       10362.571429
2021-01-14                                        8629.714286
2021-01-15                                        6335.714286
2021-01-16                                                NaN

Region                                                                 \
Item       Casos diarios anticuerpos Porcentaje de población vacunada
2021-01-09                       0.0                              NaN
2021-01-10                       0.0                              NaN
2021-01-11                       0.0                             0.87
2021-01-12                       0.0                             1.04
2021-01-13                       0.0                             1.24
2021-01-14                       0.0                             1.45
2021-01-15                       0.0                             1.64
2021-01-16                       NaN                              NaN

Region                                                                \
Item       Casos acumulados recuperados Vacunas entregadas acumulado
2021-01-09                     413216.0                          NaN
2021-01-10                     445937.0                          NaN
2021-01-11                     602343.0                     743925.0
2021-01-12                     606233.0                     743925.0
2021-01-13                     611217.0                    1103700.0
2021-01-14                     518147.0                    1139400.0
2021-01-15                     427838.0                    1139400.0
2021-01-16                          NaN                          NaN

Region
Item       Vacunas suministradas acumulado Porcentaje de vacunas suministradas
2021-01-09                             NaN                                 NaN
2021-01-10                             NaN                                 NaN
2021-01-11                        406091.0                           54.587626
2021-01-12                        488041.0                           65.603522
2021-01-13                        581638.0                           52.698922
2021-01-14                        676186.0                           59.345796
2021-01-15                        768950.0                           67.487274
2021-01-16                             NaN                                 NaN

[8 rows x 29 columns]

In [17]:
data = convida_server.get_data_items(data_items=[all_data_items[0]],
                              regions=all_regions,
                              start_date=start_date,
                              end_date=end_date)
display(data.head(2))
display(data.tail(8))

Region,CA Andalucía,CA Aragón,CA Canarias,CA Cantabria,CA Castilla y León,CA Castilla-La Mancha,CA Cataluña,CA Ceuta,CA Comunidad Foral de Navarra,CA Comunidad Valenciana,CA Comunidad de Madrid,CA Extremadura,CA Galicia,CA Islas Baleares,CA La Rioja,CA Melilla,CA País Vasco,CA Principado de Asturias,CA Región de Murcia
Item,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación
2020-11-01,0.000000,0.000000,0.000000,0.000000,0.018182,0.0,0.020000,0.0,0.0,0.014286,0.000000,0.018182,5.853333,0.02,NaN,0.0,0.000000,0.009091,0.010000
2020-11-02,0.013889,0.692308,0.005882,7.971429,2.340909,0.0,0.007143,0.0,0.9,0.000000,0.369231,0.060000,4.753333,0.01,0.8,0.0,8.354545,7.900000,0.011111

Region,CA Andalucía,CA Aragón,CA Canarias,CA Cantabria,CA Castilla y León,CA Castilla-La Mancha,CA Cataluña,CA Ceuta,CA Comunidad Foral de Navarra,CA Comunidad Valenciana,CA Comunidad de Madrid,CA Extremadura,CA Galicia,CA Islas Baleares,CA La Rioja,CA Melilla,CA País Vasco,CA Principado de Asturias,CA Región de Murcia
Item,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación,Precipitación
2021-01-09,2.000000,16.530769,3.668750,5.014286,2.172000,4.069231,16.792308,28.2,6.450,6.441667,8.9625,0.89,0.70,2.371429,11.2,0.2,2.372727,9.222222,2.440000
2021-01-10,3.067647,0.715385,2.188235,0.014286,0.058333,0.645455,2.328571,7.2,0.025,3.983333,0.0000,1.18,0.00,19.222222,0.0,1.2,0.610000,0.750000,0.820000
2021-01-11,0.347222,0.000000,0.787500,0.000000,0.024000,0.000000,0.007143,0.0,0.000,0.225000,0.0000,0.12,0.00,0.377778,0.0,2.4,0.041667,0.228571,0.011111
2021-01-12,0.008571,0.000000,1.000000,0.000000,0.032000,0.000000,0.007143,0.0,0.200,0.069231,0.0000,0.00,0.00,0.000000,0.0,0.0,0.108333,0.000000,0.000000
2021-01-13,0.000000,0.000000,0.246667,0.000000,0.008333,0.000000,0.000000,0.0,0.650,0.046154,0.0000,0.00,0.02,0.000000,0.0,0.0,0.391667,0.000000,0.000000
2021-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data = convida_server.get_data_items(data_items=all_data_items,
                              regions=all_regions,
                              start_date=start_date,
                              end_date=end_date)
display(data.head(2))
display(data.tail(8))

Region                A Coruña                                          \
Item       Letalidad acumulada Casos detectados en los últimos 14 días
2020-11-01             0.02359                                  3657.0
2020-11-02             0.02383                                  3684.0

Region                                                               \
Item       Casos acumulados Casos acumulados por 100.000 habitantes
2020-11-01          17208.0                                 1536.98
2020-11-02          17413.0                                 1555.29

Region                                                             \
Item       Media de casos detectados en 7 días Fallecidos diarios
2020-11-01                               286.0                2.0
2020-11-02                               283.6                9.0

Region                                                \
Item       Media de fallecidos en los últimos 3 días
2020-11-01                                       2.3
2020-11-02                                       4.7

Region                                                \
Item       Media de fallecidos en los últimos 7 días
2020-11-01                                       2.7
2020-11-02                                       3.1

Region                                                               \
Item       Porcentaje de nuevos fallecidos respecto de día anterior
2020-11-01                                               50.0
2020-11-02                                              220.0

Region                                       ...                Ávila  \
Item       Fallecidos en los últimos 7 días  ... Casos acumulados UCI
2020-11-01                             19.0  ...                 10.0
2020-11-02                             22.0  ...                  9.0

Region                                                     \
Item       Casos UCI por 100.000 habitantes Casos diarios
2020-11-01                             6.34          69.0
2020-11-02                             5.71          88.0

Region                                     \
Item       Casos diarios prueba antígenos
2020-11-01                            0.0
2020-11-02                            0.0

Region                                                                       \
Item       Casos diarios de pruebas desconocidas Casos diarios prueba Elisa
2020-11-01                                  11.0                        0.0
2020-11-02                                  18.0                        0.0

Region                        \
Item       Casos diarios PCR
2020-11-01              58.0
2020-11-02              70.0

Region                                                           \
Item       Media de casos PCR confirmados en los últimos 7 días
2020-11-01                                               74.0
2020-11-02                                               66.1

Region
Item       Casos diarios anticuerpos Casos acumulados recuperados
2020-11-01                       0.0                        933.0
2020-11-02                       0.0                        933.0

[2 rows x 2383 columns]

Region                A Coruña                                          \
Item       Letalidad acumulada Casos detectados en los últimos 14 días
2021-01-09             0.02022                                  3690.0
2021-01-10             0.02006                                  3894.0
2021-01-11             0.02001                                  4169.0
2021-01-12             0.02003                                  4437.0
2021-01-13             0.01972                                  4761.0
2021-01-14             0.01945                                  5145.0
2021-01-15                 NaN                                     NaN
2021-01-16                 NaN                                     NaN

Region                                                               \
Item       Casos acumulados Casos acumulados por 100.000 habitantes
2021-01-09          30759.0                                 2747.33
2021-01-10          31103.0                                 2778.06
2021-01-11          31533.0                                 2816.46
2021-01-12          32058.0                                 2863.35
2021-01-13          32655.0                                 2916.68
2021-01-14          33273.0                                 2971.88
2021-01-15              NaN                                     NaN
2021-01-16              NaN                                     NaN

Region                                                             \
Item       Media de casos detectados en 7 días Fallecidos diarios
2021-01-09                               321.0                1.0
2021-01-10                               338.0                2.0
2021-01-11                               375.4                7.0
2021-01-12                               393.6               11.0
2021-01-13                               436.7                2.0
2021-01-14                               470.7                3.0
2021-01-15                                 NaN                NaN
2021-01-16                                 NaN                NaN

Region                                                \
Item       Media de fallecidos en los últimos 3 días
2021-01-09                                       1.3
2021-01-10                                       2.0
2021-01-11                                       3.3
2021-01-12                                       6.7
2021-01-13                                       6.7
2021-01-14                                       5.3
2021-01-15                                       NaN
2021-01-16                                       NaN

Region                                                \
Item       Media de fallecidos en los últimos 7 días
2021-01-09                                       3.0
2021-01-10                                       2.7
2021-01-11                                       2.9
2021-01-12                                       4.0
2021-01-13                                       3.7
2021-01-14                                       4.1
2021-01-15                                       NaN
2021-01-16                                       NaN

Region                                                               \
Item       Porcentaje de nuevos fallecidos respecto de día anterior
2021-01-09                                               20.0
2021-01-10                                               30.0
2021-01-11                                              110.0
2021-01-12                                              170.0
2021-01-13                                               30.0
2021-01-14                                               50.0
2021-01-15                                                NaN
2021-01-16                                                NaN

Region                                       ...                Ávila  \
Item       Fallecidos en los últimos 7 días  ... Casos acumulados UCI
2021-01-09                             21.0  ...                  3.0
2021-01-10                             19.0  ...                  3.0
2021-01-11                             20.0  ...                  4.0
2021-01-12                             28.0  ...                  4.0
2021-01-13                             26.0  ...                  7.0
2021-01-14                             29.0  ...                  7.0
2021-01-15                              NaN  ...                  7.0
2021-01-16                              NaN  ...                  NaN

Region                                                     \
Item       Casos UCI por 100.000 habitantes Casos diarios
2021-01-09                             1.90         118.0
2021-01-10                             1.90         128.0
2021-01-11                             2.54         111.0
2021-01-12                             2.54          89.0
2021-01-13                             4.44          51.0
2021-01-14                             4.44           0.0
2021-01-15                             4.44           NaN
2021-01-16                              NaN           NaN

Region                                     \
Item       Casos diarios prueba antígenos
2021-01-09                            0.0
2021-01-10                            0.0
2021-01-11                            0.0
2021-01-12                            0.0
2021-01-13                            0.0
2021-01-14                            0.0
2021-01-15                            NaN
2021-01-16                            NaN

Region                                                                       \
Item       Casos diarios de pruebas desconocidas Casos diarios prueba Elisa
2021-01-09                                 108.0                        0.0
2021-01-10                                  99.0                        1.0
2021-01-11                                 104.0                        0.0
2021-01-12                                  84.0                        0.0
2021-01-13                                  47.0                        0.0
2021-01-14                                   0.0                        0.0
2021-01-15                                   NaN                        NaN
2021-01-16                                   NaN                        NaN

Region                        \
Item       Casos diarios PCR
2021-01-09              10.0
2021-01-10              28.0
2021-01-11               7.0
2021-01-12               5.0
2021-01-13               4.0
2021-01-14               0.0
2021-01-15               NaN
2021-01-16               NaN

Region                                                           \
Item       Media de casos PCR confirmados en los últimos 7 días
2021-01-09                                                8.9
2021-01-10                                               11.9
2021-01-11                                               11.9
2021-01-12                                               11.1
2021-01-13                                               10.9
2021-01-14                                                9.6
2021-01-15                                                NaN
2021-01-16                                                NaN

Region
Item       Casos diarios anticuerpos Casos acumulados recuperados
2021-01-09                       0.0                       1211.0
2021-01-10                       0.0                       1211.0
2021-01-11                       0.0                       1211.0
2021-01-12                       0.0                       1214.0
2021-01-13                       0.0                       1214.0
2021-01-14                       0.0                       1219.0
2021-01-15                       NaN                       1222.0
2021-01-16                       NaN                          NaN

[8 rows x 2383 columns]

### Testing geographical requests

In [19]:
print('Testing geographical requests...')

all_regions = Regions.get_regions('ES')

datasources = COnVIDa.get_data_items_names(DataType.GEOGRAPHICAL, language='EN')
all_data_items = []
for data_items in datasources.values():
    all_data_items += data_items

Testing geographical requests...

In [20]:
data = convida_server.get_data_items(data_items=[all_data_items[0]],
                                     regions=all_regions,
                                     language='EN')
display(data.head(2))
display(data.tail(2))

Item,Physical activity (Nivel alto),Physical activity (Nivel bajo),Physical activity (Nivel moderado),Physical activity (No consta)
Region,,,,
CA Andalucía,1207.9,2558.3,2206.7,0.0
CA Aragón,98.7,400.2,403.2,1.1

Item,Physical activity (Nivel alto),Physical activity (Nivel bajo),Physical activity (Nivel moderado),Physical activity (No consta)
Region,,,,
Ceuta,8.3,44.5,7.4,0.0
Melilla,33.9,6.1,17.9,0.0

In [21]:
data = convida_server.get_data_items(data_items=all_data_items,
                                     regions=all_regions,
                                     language='EN')
display(data.head(2))
display(data.tail(2))

Item,Physical activity (Nivel alto),Physical activity (Nivel bajo),Physical activity (Nivel moderado),Physical activity (No consta),Households by occupancy density (60 m2 o más por ocupante),Households by occupancy density (Entre 10 y menos de 20 m2 por ocupante),Households by occupancy density (Entre 20 y menos de 30 m2 por ocupante),Households by occupancy density (Entre 30 y menos de 60 m2 por ocupante),Households by occupancy density (Menos de 10 m2 por ocupante),Households by family type (1 persona),...,"Over 65 years old alone (65 años o más, Viudo/a)","Over 65 years old alone (Menos de 65 años, Casado/a)","Over 65 years old alone (Menos de 65 años, Divorciado/a)","Over 65 years old alone (Menos de 65 años, Separado/a)","Over 65 years old alone (Menos de 65 años, Soltero/a)","Over 65 years old alone (Menos de 65 años, Viudo/a)",Tobacco consumption (Exfumador),Tobacco consumption (Fumador diario),Tobacco consumption (Fumador ocasional),Tobacco consumption (Nunca ha fumado)
Region,,,,,,,,,,,,,,,,,,,,,
CA Andalucía,1207.9,2558.3,2206.7,0.0,1309.500000,1259.20,2471.483333,3266.900000,39.833333,731.866667,...,210.550000,33.566667,63.100000,23.233333,282.416667,25.483333,18.55,27.09,3.11,51.25
CA Aragón,98.7,400.2,403.2,1.1,233.833333,192.25,369.700000,497.283333,3.766667,145.833333,...,45.133333,7.516667,10.166667,4.500000,54.616667,4.366667,26.54,25.87,1.44,46.15

Item,Physical activity (Nivel alto),Physical activity (Nivel bajo),Physical activity (Nivel moderado),Physical activity (No consta),Households by occupancy density (60 m2 o más por ocupante),Households by occupancy density (Entre 10 y menos de 20 m2 por ocupante),Households by occupancy density (Entre 20 y menos de 30 m2 por ocupante),Households by occupancy density (Entre 30 y menos de 60 m2 por ocupante),Households by occupancy density (Menos de 10 m2 por ocupante),Households by family type (1 persona),...,"Over 65 years old alone (65 años o más, Viudo/a)","Over 65 years old alone (Menos de 65 años, Casado/a)","Over 65 years old alone (Menos de 65 años, Divorciado/a)","Over 65 years old alone (Menos de 65 años, Separado/a)","Over 65 years old alone (Menos de 65 años, Soltero/a)","Over 65 years old alone (Menos de 65 años, Viudo/a)",Tobacco consumption (Exfumador),Tobacco consumption (Fumador diario),Tobacco consumption (Fumador ocasional),Tobacco consumption (Nunca ha fumado)
Region,,,,,,,,,,,,,,,,,,,,,
Ceuta,8.3,44.5,7.4,0.0,4.383333,30.500000,24.016667,18.800000,6.383333,4.633333,...,1.350000,0.333333,0.533333,0.150000,1.683333,0.083333,18.62,18.66,2.13,60.59
Melilla,33.9,6.1,17.9,0.0,6.283333,27.166667,23.850000,20.433333,5.750000,4.550000,...,1.283333,0.300000,0.416667,0.133333,1.683333,0.166667,2.55,18.99,1.66,76.80

In [22]:
convida_server.init_log()
convida_server.load_data()

In [25]:
print(convida_server.get_min_date())
print(convida_server.get_max_date())
display(convida_server.get_last_update_dates())

2020-11-01
2021-01-17

                   last_update
AEMETDataSource     2021-01-17
COVID19DataSource   2021-01-17
INEDataSource       2021-01-17
MobilityDataSource  2021-01-17
MoMoDataSource      2021-01-17

In [26]:
%%time
convida_server.daily_update()
convida_server.init_log()
convida_server.load_data()
display(convida_server.get_last_update_dates())

                   last_update
AEMETDataSource     2021-01-17
COVID19DataSource   2021-01-17
INEDataSource       2021-01-17
MobilityDataSource  2021-01-17
MoMoDataSource      2021-01-17

Wall time: 40.9 ms